### ISSUE TITLE
Release v1.4.1 fails test

### ISSUE THREAD

**Issue by TonyJDavies** [nfriedly/express-slow-down#31]
Having upgraded from using version `1.4.0` in our code I'm now seeing tests timing out.

I then installed/run the code using node v14.18.3 and am seeing one of your test cases fail  too:

+ Test failure : `should decrement hits with closed response and skipFailedRequests`

<img width="640" alt="image" src="https://user-images.githubusercontent.com/40263457/189957105-f59e6fa8-4220-413f-8fa6-e649c2d41c5d.png">

The problem appears to have been caused by a https://github.com/nfriedly/express-slow-down/blob/459f2d532246c263356137dde6b840f522b6bf1d/lib/express-slow-down.js#L123 which is the only significant change since the previous revision at 1.4.0. I have no idea what fix is needed.

**Comment by nfriedly** [comment]
So, that test passed in CI on node v14.20.0 - https://github.com/nfriedly/express-slow-down/actions/runs/3011334117/jobs/4838331160

What OS are you on? I've observed some flakeyness in testing on Windows and especially MacOS, but I believe it's due to how the test suite is implemented, not an issue with the library. (It's been on my todo list to improve this.)

That clearTimeout fix *should* only affect requests where the connection timed out or otherwise closed before the slowdown ended.

Can you share what your test looks like?

**Comment by TonyJDavies** [comment]
I'm on the latest version of MacOS. Will see if I can do a bit more detective work to see what's going on in my test cases and will share if I can track down what's needed to get them working. Hopefully I can work out a minimal test case that can be shared.

**Comment by nfriedly** [comment]
Ok, it sounds like you're not the only one with this issue, #32 seems like it's probably the same thing.

I'd like to get an automated test that recreates the issue so that we can then fix it for good. To that end, I spent some time this weekend stabilizing the existing tests so that they now appear to pass reliably on windows, mac, and linux.

The one thing I want to add, that I haven't gotten to yet, is a "real world" integration test that spins up a server and makes actual HTTP requests. I have a feeling that that will be necessary to narrow this down.

Anything you can do to get me a reproducible test case would be appreciated.

**Comment by TonyJDavies** [comment]
Thankyou for looking into this. Unfortunately I've not yet got a minimal test case..

**Comment by nfriedly** [comment]
You're welcome!

@ouraios figured out on #32 that if the request body is consumed before express-slow-down runs (e.g. by using `body-parser`), that will lead to the hanging bug. v1.4.2 fixes this.

However, I should mention that it would make more sense to have `express-slow-down` run before something like `body-parser` because it can't provide any protection against a malicious user sending tons of uploads if it runs after.

**Comment by TonyJDavies** [comment]
Awesome - Works in our case too. Much appreciated.
